### ISSUE TITLE
pending transactions

### ISSUE THREAD

**Issue by Eika4** [petrachor/petrachor#18]
There seems to be a communication issue between nodes for pending transactions. Some nodes return pending transactions, and some do not when using eth_pendingTransactions

**Comment by ruellm** [comment]
Here is the result of the investigation and some recommendations.

- The eth_pendingTransaction endpoint has no issue, but that is how it was designed based on ethereum specifications.; which is to display the transactions (from transaction pool) for only those accounts that a node is managing (local accounts).
That is the main reason that some nodes does not display the pending transactions, and there is no issue during synching.

- So I did an investigation on how the other applications such as etherscan and blockscout handled it.
(1) blockscout is using an endpoint called "txpool_content", which is basically the same as that of eth_pendingTransaction but displays ALL transactions in the transaction pool instead.

curl -X POST -H "Content-Type: application/json"  --data '{"jsonrpc":"2.0","method":"txpool_content","params":[],"id":67}'  http://localhost:8545/

Unfortunately, this endpoint is not available in petrachor, or aleth or any non ethereum client except for geth.

(2) Another option is to use the filters and listen/polls to it, both eth_newPendingTransactionFilter and eth_getFilterChanges are supported in petrachor, but the app developer needs to do extra work since eth_getFilterChanges() returns only the transaction hash so the web developer needs to retrieve the transaction information by that hash. 3 steps.
Petrachor supports these endpoints

(3) Subscribing thru Websockets.
Petrachor does not have websocket support.

- Therefore to support pending transactions our options are.
(1) implement 'txpool_content' as a new endpoint
(2) implement filters and pooling from the blockscout or application side
(3) supports Websocket in petrachor.

My recommendation is to support websockets.
